{% set name = "pytorch-tabnet" %}
{% set version = "4.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytorch_tabnet-{{ version }}.tar.gz
  sha256: 18887b993a8bf86ec05a576b5cf93f09e08b778cd9f418c5b254b6566df673a5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - poetry >=0.12
  run:
    - python >=3.6
    - numpy >=1.17,<2.0
    - scikit-learn >0.21
    - scipy >1.4
    - pytorch >=1.2,<2.0
    - tqdm >=4.36,<5.0

test:
  imports:
    - pytorch_tabnet
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dreamquark-ai/tabnet
  summary: PyTorch implementation of TabNet
  license: MIT
  description: |
    This is a pyTorch implementation of Tabnet (Arik, S. O., & Pfister, T. (2019). 
    TabNet: Attentive Interpretable Tabular Learning. arXiv preprint arXiv:1908.07442.) 
    https://arxiv.org/pdf/1908.07442.pdf.
  license_file: LICENSE
  dev_url: https://github.com/dreamquark-ai/tabnet
  doc_url: https://github.com/dreamquark-ai/tabnet

extra:
  recipe-maintainers:
    - sugatoray
    - Optimox
    - Hartorn
    - eduardocarvp
